#!/bin/sh
function buildNrun() {
	cabal build -v mptcp-pm
	if [ $? -eq 0 ]; then
    # with our changes sudo should not be necessaery anymore
    cabal run mptcp-pm -- $@
		# ./daemon daemon $@
	fi
}

# function rundaemon() {
# 	cabal new-build
# 	sudo setcap cap_net_admin+ep ./dist-newstyle/build/x86_64-linux/ghc-8.6.3/netlink-pm-1.0.0/x/daemon/build/daemon/daemon
# 	cabal new-run
# }
